networks:
  custom_net:
     ipam:
       driver: default
       config:
          - subnet: 172.0.0.0/16



volumes:
  files:
    driver: local
  mysql:
    driver: local
  backup:
    driver: local
  redis:
    driver: local


services:
   nginx:
     image: jwilder/nginx-proxy
     networks :
       custom_net:
               ipv4_address: 172.0.0.10   ## 172.0.0.1 already used

     container_name: nginx
     volumes:
       - /var/run/docker.sock:/tmp/docker.sock:ro
       - /root/Nginx/client_max_body_size.conf:/etc/nginx/conf.d/client_max_body_size.conf:ro
       - /etc/nginx/certs ## SSL
       - /etc/nginx/vhost.d ## SSL
       - /usr/share/nginx/html ## SSL
         #- /root/nginx/vhost.d:/etc/nginx/conf
     ports:
       - 80:80
       - 443:443 ## SSL


   letsencrypt:
    image:  jrcs/letsencrypt-nginx-proxy-companion:v1.13.1

    networks :
       custom_net:
          ipv4_address: 172.0.0.2


    container_name: ssl
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/acme.sh
    volumes_from:
      - nginx
    environment:
      - DEFAULT_EMAIL=antoine@morbois.fr


   jekyll:
     image: jekyll/jekyll:3.8
     networks :
       custom_net:
        ipv4_address: 172.0.0.3
     container_name: blog
     restart: always
     volumes:
       - /root/Blog/:/srv/jekyll
     expose:
       - 4000
     environment:
       - JEKYLL_UID=1001
       - JEKYLL_GID=1001
       - VIRTUAL_HOST=morbois.fr
       - VIRTUAL_PORT=4000
       - LETSENCRYPT_HOST=morbois.fr
     command: ["sh","-c"," bundle pack; jekyll serve"]

   owncloud:
    image: owncloud/server:${OWNCLOUD_VERSION}
    networks :
      custom_net:
       ipv4_address: 172.0.0.4
    container_name: owncloud
    restart: always
    #ports:
            #  - ${HTTP_PORT}:8080
    expose:
      - 8080
    depends_on:
      - db
      - redis
    environment:
      - OWNCLOUD_DOMAIN=${OWNCLOUD_DOMAIN}
      - OWNCLOUD_DB_TYPE=mysql
      - OWNCLOUD_DB_NAME=<pwd>
      - OWNCLOUD_DB_USERNAME=<pwd>
      - OWNCLOUD_DB_PASSWORD=<pwd>
      - OWNCLOUD_DB_HOST=db
      - OWNCLOUD_ADMIN_USERNAME=${ADMIN_USERNAME}
      - OWNCLOUD_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - OWNCLOUD_MYSQL_UTF8MB4=true
      - OWNCLOUD_REDIS_ENABLED=true
      - OWNCLOUD_REDIS_HOST=redis
      - VIRTUAL_HOST=owncloud.morbois.fr
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=owncloud.morbois.fr

    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
            - files:/mnt/data

   db:
    image: webhippie/mariadb:latest
    networks :
     custom_net:
       ipv4_address: 172.0.0.5
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=<pwd>
      - MARIADB_USERNAME=<pwd>
      - MARIADB_PASSWORD=<pwd>
      - MARIADB_DATABASE=<pwd>
      - MARIADB_MAX_ALLOWED_PACKET=128M
      - MARIADB_INNODB_LOG_FILE_SIZE=64M
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql:/var/lib/mysql
      - backup:/var/lib/backup

   redis:
    image: webhippie/redis:latest
    networks :
     custom_net:
       ipv4_address: 172.0.0.6
    restart: always
    environment:
      - REDIS_DATABASES=1
    healthcheck:
      test: ["CMD", "/usr/bin/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis:/var/lib/redis

   pihole:
        container_name: pihole
        networks :
         custom_net:
          ipv4_address: 172.0.0.7
        image: pihole/pihole:latest
        environment:
         - VIRTUAL_HOST=pihole.morbois.fr
         - LETSENCRYPT_HOST=pihole.morbois.fr
           #- VIRTUAL_PORT=443/tcp
           #- VIRTUAL_PORT=53/tcp
           #- VIRTUAL_PORT=53/udp
           #- VIRTUAL_PORT=67/udp
         - VIRTUAL_PORT=80
         - TZ= 'Europe/Paris'
         - WEBPASSWORD= 'DP6=pbDRH8'
        expose:
           - 80
           - 443
           - 53/tcp
           - 53/udp
           - 67/udp
           #ports:
           #- 80/tcp
           #- 443/tcp
           #- 53/tcp
           #- 53/udp
           #- 67/udp

        volumes:
         - './etc-pihole/:/etc/pihole/'
         - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
           #cap_add:
           #- NET_ADMIN
        restart: unless-stopped


   wireguard:
    image: ghcr.io/linuxserver/wireguard
    networks :
     custom_net:
        ipv4_address: 172.0.0.8
    container_name: wireguard
    depends_on:
      - pihole
    dns:
        # - pihole
      - 172.0.0.7
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - VIRTUAL_HOST=vpn.morbois.fr
      - VIRTUAL_PORT=51820
      - LETSENCRYPT_HOST=vpn.morbois.fr
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
      - SERVERURL=auto   #vpn.morbois.com #optional
      - SERVERPORT=51820 #optional
      - PEERS=Antoine #optional
      - PEERDNS=auto #optional
        #- INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - /root/Wireguard/:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    expose:
      - 51820
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped